# Generated by Django 3.1.5 on 2021-01-08 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_contact1_timestamp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact1',
            old_name='phonw',
            new_name='phone',
        ),
    ]
